SECRET_KEY = '$2a$12$9qHkfxqa/CIeh0nVVV1RN.mvcc4TR3F2/VeFYgUNMvWghYYPUwNue'
DEPLOY_ENV = 'local'

DEBUG = True
TESTING = False

POSTGRES_HOST = 'localhost'
POSTGRES_DATABASE = 'peerrev'
POSTGRES_USER = 'peerrev'
POSTGRES_PASSWORD = 'peerrev'

UPLOAD_FOLDER = './uploads'
MAX_CONTENT_LENGTH =  10000000
